name: PyPi Build and Deploy 🐍📦

on:
  release:
    types: [published]
  # use this for testing
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: Build and publish MyProxyClient on PyPi
    runs-on: ubuntu-latest
    # use the new Trusted Publishers feature
    # details at https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build
          --source
          --binary
          --out-dir dist/
          .
      #- name: Publish distribution 📦 to Test PyPI
      #  uses: pypa/gh-action-pypi-publish@master
      #  with:
      #    password: ${{ secrets.test_pypi_password }}
      #    repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
      # this is the old token and password way;
      # we are using the new Truster Publishers (see above)
      #  with:
      #    user: __token__
      #    password: ${{ secrets.pypi_password }}
